@extends('pdf.layouts.institucional', ['tituloPdf' => 'Reporte de Seguimiento y Gestión'])
@section('content')
<div class="report-hero"><div class="report-hero-main"><div class="eyebrow">Sistema de Gestión de Casos Jurídicos</div><h1>Reporte de Seguimiento y Gestión</h1></div><div class="report-hero-meta"><strong>Fecha de generación</strong><br>{{ $generadoEn?->format('d/m/Y · H:i') }}<br>America/Bogota · Fecha de solicitud</div></div>
<div class="filters"><strong>Filtros aplicados</strong><br>@foreach($filtrosAplicados as $nombre => $valor)<span class="filter-item"><b>{{ $nombre }}:</b> {{ $valor }}</span>@endforeach</div>
<div class="summary"><div class="metric"><strong>{{ $resumen['total'] }}</strong><span>Total de casos</span></div><div class="metric"><strong>{{ $resumen['activos'] }}</strong><span>Casos activos</span></div><div class="metric"><strong>{{ $resumen['proximos'] }}</strong><span>En riesgo</span></div><div class="metric"><strong>{{ $resumen['vencidos'] }}</strong><span>ANS vencidos</span></div><div class="metric"><strong>{{ $resumen['tareas_pendientes'] }}</strong><span>Tareas pendientes</span></div></div>

<section class="section"><div class="section-heading"><h2>Situación ANS</h2><span>Resumen ejecutivo</span></div><div class="summary">@foreach([['Vigente','vigente','badge-success'],['Preventivo','preventivo','badge-warning'],['Crítico','critico','badge-warning'],['Vencido','vencido','badge-danger'],['Cumplido','cumplido','badge-success'],['Incumplido','incumplido','badge-danger']] as [$label,$key,$class])<div class="metric"><strong>{{ $resumen['por_ans'][$key] ?? 0 }}</strong><span class="badge {{ $class }}">{{ $label }}</span></div>@endforeach</div></section>

<section class="section"><div class="section-heading"><h2>Resultados por tipo</h2><span>Estado y ANS consolidados</span></div><div class="table-wrap"><table><thead><tr><th>Tipo</th><th class="number">Total</th><th class="number">Pendiente</th><th class="number">En proceso</th><th class="number">Completado</th><th class="number">Finalizado</th><th class="number">En riesgo</th><th class="number">Vencido</th></tr></thead><tbody>@forelse($porTipo->filter(fn($fila) => $fila->total) as $fila)<tr><td class="cell-primary">{{ $fila->tipo->nombre }}</td><td class="number">{{ $fila->total }}</td>@foreach($fila->estados as $n)<td class="number">{{ $n }}</td>@endforeach<td class="number">{{ $fila->ans['preventivo'] + $fila->ans['critico'] }}</td><td class="number">{{ $fila->ans['vencido'] + $fila->ans['incumplido'] }}</td></tr>@empty<tr><td colspan="8" class="empty">No hay resultados para los filtros aplicados.</td></tr>@endforelse</tbody></table></div></section>

<section class="section"><div class="section-heading"><h2>Seguimiento por responsable</h2><span>Carga operativa y alertas</span></div><div class="table-wrap"><table><thead><tr><th>Responsable</th><th>Rol</th><th class="number">Casos</th><th class="number">Pendientes</th><th class="number">Completadas</th><th class="number">En riesgo</th><th class="number">Vencidos</th></tr></thead><tbody>@forelse($responsables as $fila)<tr><td class="cell-primary">{{ $fila->usuario->name }}</td><td><span class="badge">{{ $fila->usuario->role?->nombre }}</span></td><td class="number">{{ $fila->casos_asociados }}</td><td class="number">{{ $fila->tareas_pendientes }}</td><td class="number">{{ $fila->tareas_completadas }}</td><td class="number">{{ $fila->casos_proximos }}</td><td class="number">{{ $fila->casos_vencidos }}</td></tr>@empty<tr><td colspan="7" class="empty">No hay responsables para los filtros aplicados.</td></tr>@endforelse</tbody></table></div></section>

<section class="section"><div class="section-heading"><h2>Casos que requieren atención</h2><span>Vencidos, críticos, preventivos y tareas antiguas</span></div>
@forelse($casosAtencion as $caso) @include('seguimiento.partials.pdf-case-card', ['caso' => $caso, 'atencion' => true]) @empty<div class="case-card"><div class="empty">No hay casos que requieran atención inmediata.</div></div>@endforelse
</section>

<section class="section"><div class="section-heading"><h2>Detalle de casos</h2><span>{{ $casos->count() }} resultado(s)</span></div>
@forelse($casos as $caso) @include('seguimiento.partials.pdf-case-card', ['caso' => $caso, 'atencion' => false]) @empty<div class="case-card"><div class="empty">No hay casos para los filtros aplicados.</div></div>@endforelse
</section>
@endsection
